name: Deploy Javadoc
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # if you have a protection rule on your repository, you'll need to give write permission to the workflow.
    steps:
      - name: Build
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: .
          recurse: true
          output_dir: ./docs
