name: Deploy JSDoc
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./src
          output_dir: ./docs
          template: minami
      - name: Output folders with base path
        run: find ./docs | grep html
      - name: Output folders with base path
        run: cat ./docs/index.html
      - name: Deploy
        uses: EndBug/add-and-commit@v9
        with:
          add: 'docs'
          message: Update JSDoc
          default_author: github_actions
