name: Deploy JSDoc
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./src
          output_dir: ./docs
          template: minami
      - name: Output folders with base path
        run: find ./docs | grep html
      - name: Output folders with base path
        run: cat ./docs/index.html
      - name: Deploy
        run: |
          git config --local user.email "craig.gorman.au@gmail.com"
          git config --local user.name "gormanlearncode"
          git add ./docs
          git commit -m "Add changes"
          git pull --rebase
          git push
